export {default as Header} from './Header/Header.jsx'
export {default as Home} from './Home/Home.jsx'
export {default as About} from './About/About.jsx'
export {default as Footer} from './Footer/Footer.jsx'
export {default as Contact} from './Contact/Contact.jsx'
export {default as ErrorPage} from './Error/Error.jsx'
export {default as Login} from './Login/Login.jsx'
export {default as Signup} from './Signup/Signup.jsx' 